version: '3.1'
services:
  #######################################
  # MongoDB server
  #######################################
  mongo:
    image: mongo
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-volume:
